"""
ROIN WORLD FZE — Certificate Requests Handler
===============================================
Employment Confirmation: instant PDF
Salary Certificate: HR must enable per employee
Experience Letter: requires HR approval
"""

import os, io, secrets
from datetime import datetime
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ConversationHandler, CallbackQueryHandler, MessageHandler, filters
from config import get_sheet
from fpdf import FPDF
from font_utils import add_dejavu

CERT_LANG = 300
CERT_BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def bm(): return InlineKeyboardButton("↩️ Main Menu", callback_data="back_to_menu")

LANG_LABELS = {"EN": "🇬🇧 English", "AR": "🇪🇬 Arabic", "RU": "🇷🇺 Russian"}


def _find_ec(tid):
    for i, r in enumerate(get_sheet("User_Registry").get_all_values()):
        if i == 0: continue
        if r[1].strip() == str(tid): return r[0].strip()
    return None


def _get_emp(ec):
    for r in get_sheet("Employee_DB").get_all_records():
        if str(r.get("Emp_Code", "")).strip() == str(ec):
            return r
    return None


def _logo_path():
    p = os.path.join(CERT_BASE_DIR, "company_logo.png")
    return p if os.path.exists(p) else None


# ── PDF generation ─────────────────────────────────────────────────────────────

def _safe(text):
    if not text: return ""
    text = str(text)
    for old, new in {"\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
                     "\u201c": '"', "\u201d": '"', "\u00a0": " "}.items():
        text = text.replace(old, new)
    return text.encode('latin-1', errors='replace').decode('latin-1')


class CertPDF(FPDF):
    def __init__(self, logo_path=None):
        super().__init__()
        self.logo_path = logo_path

    def header(self):
        if self.logo_path:
            self.image(self.logo_path, x=85, y=8, w=25)
            self.ln(28)
        else:
            self.ln(10)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 6, "ROIN WORLD FZE EGYPT BRANCH", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, _safe("Building No 1, Gamal Abdel Nasser Street - El Dabaa - Matrouh"),
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, "info.egypt@roinworld.com     www.roinworld.com",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(15, self.get_y() + 2, 195, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4, "Generated by ROIN WORLD FZE HR System", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, _safe(f"Generated: {datetime.now().strftime('%d/%m/%Y %H:%M')}"), align="C")


def _generate_employment_cert(emp, lang="EN"):
    pdf = CertPDF(logo_path=_logo_path())
    add_dejavu(pdf)
    pdf.add_page()

    # Choose font family: DejaVu supports Cyrillic; Helvetica for Latin-only content
    ff = "DejaVu" if lang == "RU" else "Helvetica"
    s  = (lambda t: str(t) if t else "") if lang == "RU" else _safe

    if lang == "EN":
        title   = "EMPLOYMENT CONFIRMATION CERTIFICATE"
        to_whom = "TO WHOM IT MAY CONCERN"
        body    = (
            f"This is to certify that {s(emp.get('Full_Name',''))} "
            f"(Employee Code: {s(str(emp.get('Emp_Code','')))}) "
            f"is employed at ROIN WORLD FZE as {s(emp.get('Job_Title',''))} "
            f"in the {s(emp.get('Department',''))} Department.\n\n"
            f"Employment Start Date: {s(emp.get('Hire_Date',''))}\n"
            f"Contract Type: {s(emp.get('Contract_Type',''))}\n\n"
            f"This certificate is issued upon the request of the employee for all "
            f"official purposes.")
    elif lang == "RU":
        title   = "СПРАВКА О ТРУДОУСТРОЙСТВЕ"
        to_whom = "КОМУ СЛЕДУЕТ"
        body    = (
            f"Настоящим удостоверяем, что {s(emp.get('Full_Name',''))} "
            f"(Код сотрудника: {s(str(emp.get('Emp_Code','')))}) "
            f"является сотрудником компании ROIN WORLD FZE на должности "
            f"{s(emp.get('Job_Title',''))} в отделе {s(emp.get('Department',''))}.\n\n"
            f"Дата начала работы: {s(emp.get('Hire_Date',''))}\n"
            f"Тип контракта: {s(emp.get('Contract_Type',''))}\n\n"
            f"Данная справка выдана по запросу сотрудника для официальных целей.")
    else:  # AR — rendered left-to-right with latin font (limitation without Arabic font)
        title   = "SHAHADAT TAAKEED AL-ISTIKHDAAM"
        to_whom = "ILA MAN YA'HUMMAHU AL-AMR"
        body    = (
            f"Nushhad bi-anna {s(emp.get('Full_Name',''))} "
            f"(Code: {s(str(emp.get('Emp_Code','')))}) "
            f"ya'mal ladayna fi ROIN WORLD FZE "
            f"bi-safatihi {s(emp.get('Job_Title',''))} "
            f"fi qism {s(emp.get('Department',''))}.\n\n"
            f"Tarikh al-tawdhif: {s(emp.get('Hire_Date',''))}\n"
            f"Naw' al-aqd: {s(emp.get('Contract_Type',''))}\n\n"
            f"Sudira hadha al-shahadat bi-talab al-muwazzaf li-jami' al-agh-rad al-rasmiyya.")

    pdf.set_font(ff, "B", 16)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(3)
    pdf.set_font(ff, "B", 11)
    pdf.cell(0, 8, to_whom, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    pdf.set_font(ff, "", 11)
    pdf.set_fill_color(230, 230, 230)
    details_label = "  СВЕДЕНИЯ О СОТРУДНИКЕ" if lang == "RU" else "  EMPLOYEE DETAILS"
    pdf.cell(0, 8, details_label, new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(3)
    if lang == "RU":
        field_labels = [("Имя", "Full_Name"), ("Код", "Emp_Code"),
                        ("Отдел", "Department"), ("Должность", "Job_Title"),
                        ("Гражданство", "Nationality"), ("Дата найма", "Hire_Date"),
                        ("Тип контракта", "Contract_Type")]
    else:
        field_labels = [("Name", "Full_Name"), ("Code", "Emp_Code"),
                        ("Department", "Department"), ("Job Title", "Job_Title"),
                        ("Nationality", "Nationality"), ("Hire Date", "Hire_Date"),
                        ("Contract Type", "Contract_Type")]
    for label, key in field_labels:
        pdf.set_font(ff, "B", 10)
        pdf.cell(50, 7, f"  {label}:")
        pdf.set_font(ff, "", 10)
        pdf.cell(0, 7, s(str(emp.get(key, "-"))), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font(ff, "", 10)
    for para in body.split("\n"):
        pdf.multi_cell(0, 7, s(para) if para else "")
    pdf.ln(10)

    pdf.set_font(ff, "", 10)
    today = datetime.now().strftime("%d/%m/%Y")
    date_label = f"Дата: {today}" if lang == "RU" else f"Date: {today}"
    sig_label  = "Подпись:" if lang == "RU" else "Authorized Signature:"
    pdf.cell(95, 7, date_label)
    pdf.cell(95, 7, sig_label, align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Embed HR Manager signature if provided
    hr_sig_bytes = emp.get("_hr_sig_bytes") if emp else None
    hr_sig_text  = emp.get("_hr_sig_text",  "") if emp else ""
    if hr_sig_bytes:
        try:
            img_io = io.BytesIO(hr_sig_bytes)
            pdf.image(img_io, x=pdf.w - pdf.r_margin - 45, y=pdf.get_y(), h=12)
            pdf.ln(14)
        except Exception:
            pdf.set_font(ff, "I", 8)
            pdf.cell(0, 5, s(hr_sig_text or "HR Manager"), align="R",
                     new_x="LMARGIN", new_y="NEXT")
    elif hr_sig_text:
        pdf.set_font(ff, "I", 8)
        pdf.cell(0, 5, s(hr_sig_text), align="R", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 7, "___________________", align="R", new_x="LMARGIN", new_y="NEXT")

    hr_title = "Менеджер по персоналу — ROIN WORLD FZE" if lang == "RU" else "HR Manager — ROIN WORLD FZE"
    pdf.set_font(ff, "", 10)
    pdf.cell(0, 7, hr_title, align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    ver_code = f"SIG-{secrets.token_hex(4).upper()}"
    pdf.set_font(ff, "I", 7)
    pdf.cell(0, 4, f"Verified: {ver_code}", align="C")

    return pdf.output()


# ── Bot handlers ────────────────────────────────────────────────────────────────

async def cert_menu_handler(update, context):
    q = update.callback_query; await q.answer()
    kb = [
        [InlineKeyboardButton("📜 Employment Confirmation", callback_data="cert_employment")],
        [InlineKeyboardButton("💰 Salary Certificate",      callback_data="cert_salary")],
        [InlineKeyboardButton("🏅 Experience Letter",       callback_data="cert_experience")],
        [InlineKeyboardButton("↩️ Back", callback_data="back_to_menu"), bm()],
    ]
    await q.edit_message_text(
        "📜 Certificate Requests\n\nSelect the certificate type:",
        reply_markup=InlineKeyboardMarkup(kb))


async def cert_employment_handler(update, context):
    """Employment cert: language selection → generate PDF."""
    q = update.callback_query; await q.answer()
    ec = _find_ec(str(q.from_user.id))
    if not ec:
        await q.edit_message_text("❌ Not registered.", reply_markup=InlineKeyboardMarkup([[bm()]])); return
    context.user_data["cert_ec"] = ec
    kb = [
        [InlineKeyboardButton(LANG_LABELS["EN"], callback_data="cert_emp_EN")],
        [InlineKeyboardButton(LANG_LABELS["RU"], callback_data="cert_emp_RU")],
        [InlineKeyboardButton(LANG_LABELS["AR"], callback_data="cert_emp_AR")],
        [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()],
    ]
    await q.edit_message_text(
        "📜 Employment Confirmation\n\nSelect language:",
        reply_markup=InlineKeyboardMarkup(kb))
    return CERT_LANG


async def cert_emp_lang_sel(update, context):
    """Generate and send the employment cert PDF."""
    q = update.callback_query; await q.answer()
    lang = q.data.replace("cert_emp_", "")
    ec   = context.user_data.get("cert_ec")
    await q.edit_message_text("⏳ Generating certificate...")
    try:
        emp = _get_emp(ec)
        if not emp:
            await q.edit_message_text("❌ Employee record not found.",
                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]])); return ConversationHandler.END
        pdf_bytes = _generate_employment_cert(emp, lang)
        filename  = f"{ec}-Employment-{datetime.now().strftime('%d%m%Y')}.pdf"
        from drive_utils import upload_to_drive
        drive_url = upload_to_drive(pdf_bytes, filename, "certificates")
        if drive_url:
            await q.edit_message_text(
                f"✅ Certificate generated!\nLanguage: {LANG_LABELS.get(lang, lang)}",
                reply_markup=InlineKeyboardMarkup([
                    [InlineKeyboardButton("📄 View PDF", url=drive_url)],
                    [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))
        else:
            await q.message.reply_document(
                document=io.BytesIO(pdf_bytes),
                filename=filename,
                caption=f"📜 Employment Confirmation Certificate ({LANG_LABELS.get(lang, lang)})")
            await q.edit_message_text(
                f"✅ Certificate generated!\nLanguage: {LANG_LABELS.get(lang, lang)}",
                reply_markup=InlineKeyboardMarkup([
                    [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))
    except Exception as e:
        await q.edit_message_text(f"❌ Error: {e}",
            reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))
    return ConversationHandler.END


async def cert_salary_handler(update, context):
    q = update.callback_query; await q.answer()
    ec = _find_ec(str(q.from_user.id))
    emp = _get_emp(ec) if ec else None
    # Check if HR has enabled salary cert for this employee
    # Field: Has_Salary_Cert_Enabled or similar — check Annual_Leave_Balance as proxy
    # For now check if employee record exists and has a note "salary_cert:yes"
    notes = str(emp.get("Notes", "")).lower() if emp else ""
    enabled = "salary_cert:yes" in notes or "salary_cert:1" in notes
    if enabled:
        await q.edit_message_text(
            "💰 Salary Certificate\n\nYour salary certificate request has been noted.\n"
            "Please collect it from the HR office.",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))
    else:
        await q.edit_message_text(
            "💰 Salary Certificate\n\n⚠️ This certificate requires HR authorization.\n\n"
            "Please contact HR via 💬 Contact HR or visit the HR office to request this certificate.\n"
            "HR will enable it for you once approved.",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))


async def cert_experience_handler(update, context):
    q = update.callback_query; await q.answer()
    await q.edit_message_text(
        "🏅 Experience Letter\n\n⚠️ This letter requires HR approval.\n\n"
        "Experience letters are issued:\n"
        "• Upon termination/resignation\n"
        "• After minimum 1 year of employment\n\n"
        "Please submit your request via 💬 Contact HR.",
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("↩️ Back", callback_data="menu_certificates"), bm()]]))


async def cert_back_to_menu(update, context):
    from bot import build_inline_menu
    q = update.callback_query; await q.answer()
    role = "Employee"
    for i, r in enumerate(get_sheet("User_Registry").get_all_values()):
        if i == 0: continue
        if r[1].strip() == str(q.from_user.id): role = r[3].strip(); break
    await q.edit_message_text("Choose an option:", reply_markup=build_inline_menu(role))
    return ConversationHandler.END


def get_cert_handler():
    return ConversationHandler(
        entry_points=[CallbackQueryHandler(cert_employment_handler, pattern="^cert_employment$")],
        states={
            CERT_LANG: [
                CallbackQueryHandler(cert_emp_lang_sel,  pattern="^cert_emp_(EN|AR|RU)$"),
                CallbackQueryHandler(cert_back_to_menu,  pattern="^back_to_menu$"),
                CallbackQueryHandler(cert_menu_handler,  pattern="^menu_certificates$"),
            ],
        },
        fallbacks=[MessageHandler(filters.COMMAND, cert_back_to_menu)],
        per_message=False,
    )


def get_cert_static_handlers():
    """Non-conversation handlers for cert menu and simple cert screens."""
    return [
        CallbackQueryHandler(cert_menu_handler,       pattern="^menu_certificates$"),
        CallbackQueryHandler(cert_salary_handler,     pattern="^cert_salary$"),
        CallbackQueryHandler(cert_experience_handler, pattern="^cert_experience$"),
    ]
