"""
One-time script: generate a sample JD PDF for employee 1011 - Mona Farag Hamid Korani.
Run: python3 generate_sample_jd.py
Output: JD-EGK-1011-Mona_Farag.pdf
"""

from fpdf import FPDF
from datetime import datetime
import os

BASE = os.path.dirname(os.path.abspath(__file__))
LOGO = os.path.join(BASE, "company_logo.png")


def safe(text):
    """Strip characters Helvetica cannot render."""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
        "\u00b7": "*", "\u00a0": " ",
    }
    t = str(text)
    for old, new in replacements.items():
        t = t.replace(old, new)
    return t.encode("latin-1", errors="replace").decode("latin-1")


class JDPDF(FPDF):
    def header(self):
        if os.path.exists(LOGO):
            self.image(LOGO, x=85, y=8, w=25)
            self.ln(28)
        else:
            self.ln(10)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 6, "ROIN WORLD FZE EGYPT BRANCH", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, "Building No 1, Gamal Abdel Nasser Street - El Dabaa - Matrouh",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, "info.egypt@roinworld.com     www.roinworld.com",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(15, self.get_y() + 2, 195, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4,
            "This job description is not exhaustive and may be updated at any time by management.",
            align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4,
            safe(f"Generated by ROIN WORLD FZE HR System  -  {datetime.now().strftime('%d/%m/%Y')}"),
            align="C")


def section_title(pdf, title):
    pdf.set_fill_color(220, 220, 220)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, safe(f"  {title}"), new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)


def field_row(pdf, label, value, label_w=55):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(label_w, 7, safe(f"  {label}:"))
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, safe(str(value)), new_x="LMARGIN", new_y="NEXT")


def generate_jd():
    pdf = JDPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "JOB DESCRIPTION", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, "Document No: JD-EGK-1011     Effective Date: 01/01/2026     Rev: 01",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Position Information
    section_title(pdf, "POSITION INFORMATION")
    field_row(pdf, "Employee Name",    "Mona Farag Hamid Korani")
    field_row(pdf, "Employee Code",    "1011")
    field_row(pdf, "Job Title",        "Food Production Coordinator")
    field_row(pdf, "Department",       "Egyptian Kitchen")
    field_row(pdf, "Reports To",       "Head Chef - Egyptian Kitchen")
    field_row(pdf, "Work Location",    "El Dabaa Nuclear Power Plant Site, Matrouh")
    field_row(pdf, "Employment Type",  "Full-Time")
    field_row(pdf, "Grade / Level",    "Grade 4 - Specialist")
    pdf.ln(4)

    # Job Summary
    section_title(pdf, "1. JOB SUMMARY")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, safe(
        "The Food Production Coordinator is responsible for managing daily meal production "
        "workflows in the Egyptian Kitchen, ensuring that all meals produced meet the company's "
        "quality, quantity, and safety standards. This role plays a key operational part in "
        "delivering over 30,000 meals per day to the El Dabaa Nuclear Power Plant workforce, "
        "coordinating between kitchen sections, supervising production staff, and maintaining "
        "full compliance with HACCP food safety regulations."
    ))
    pdf.ln(4)

    # Key Responsibilities
    section_title(pdf, "2. KEY RESPONSIBILITIES")
    tasks = [
        "Coordinate the daily meal production schedule to ensure on-time delivery of all meals across all shifts.",
        "Supervise kitchen production staff and assign tasks according to daily workload and production targets.",
        "Monitor food quality and presentation standards at every stage of the production cycle.",
        "Ensure full compliance with HACCP food safety regulations and internal hygiene SOPs.",
        "Track raw ingredient inventory levels and coordinate with the procurement team for timely replenishment.",
        "Prepare daily and weekly production reports for the Head Chef and Kitchen Management.",
        "Conduct on-the-job training for newly hired kitchen staff on procedures, recipes, and safety protocols.",
        "Coordinate production flow between hot kitchen, cold kitchen, and pastry sections.",
        "Monitor cooking temperatures, chilling cycles, and food storage conditions at all times.",
        "Implement and enforce portion control procedures to minimize waste and control food cost.",
        "Manage special dietary requirements (low-sodium, vegetarian, diabetic) and communicate with relevant sections.",
        "Oversee daily kitchen cleaning schedules and ensure all workstations meet sanitation standards.",
        "Liaise with the receiving department to inspect incoming ingredients and reject non-conforming deliveries.",
        "Monitor kitchen equipment condition and promptly report maintenance or repair needs to the facility team.",
        "Participate in seasonal menu planning meetings and provide operational feasibility feedback.",
        "Record daily production output data in the company system accurately and on time.",
        "Manage staff daily attendance records and coordinate cover for absences to maintain production continuity.",
        "Coordinate with the nutrition team to ensure all meals meet specified caloric and nutritional values.",
        "Drive waste reduction initiatives and contribute to achieving monthly food cost targets.",
        "Prepare comprehensive end-of-shift handover reports for the incoming shift coordinator.",
    ]
    pdf.set_font("Helvetica", "", 10)
    for i, task in enumerate(tasks, 1):
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 6, safe(f"{i}.  {task}"))
    pdf.ln(4)

    # Qualifications
    section_title(pdf, "3. REQUIRED QUALIFICATIONS")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "  Education:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(10, 6, "")
    pdf.cell(0, 6, "Diploma or Bachelor's degree in Food Science, Hospitality Management, or related field.",
             new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "  Experience:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(10, 6, "")
    pdf.cell(0, 6, "Minimum 3 years in food production, industrial catering, or kitchen operations.",
             new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "  Skills:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    skills_list = [
        "Solid knowledge of HACCP and food safety standards",
        "Team supervision and coordination",
        "Report writing and basic data entry",
        "Arabic (fluent)  -  Russian (basic)  -  English (intermediate)",
    ]
    for sk in skills_list:
        pdf.cell(10, 6, "")
        pdf.cell(0, 6, safe(f"- {sk}"), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "  Preferred:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    preferred_list = [
        "Prior experience in large-scale industrial or institutional catering (1,000+ meals/day)",
        "HACCP or Food Handler certification",
    ]
    for pr in preferred_list:
        pdf.cell(10, 6, "")
        pdf.cell(0, 6, safe(f"- {pr}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Working Conditions
    section_title(pdf, "4. WORKING CONDITIONS")
    conditions = [
        ("Working Hours",        "8:00 AM - 5:00 PM, 6 days per week (shift rotation applies)"),
        ("Work Environment",     "Industrial kitchen / production facility - standing for extended periods"),
        ("Special Requirements", "Personal Protective Equipment (PPE) required at all times on site"),
        ("Physical Demands",     "Ability to lift up to 20 kg; exposure to heat and cold environments"),
    ]
    for lbl, val in conditions:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 6, safe(f"  - {lbl}:"))
        pdf.set_font("Helvetica", "", 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 6, safe(f"    {val}"))
    pdf.ln(4)

    # Approval
    section_title(pdf, "5. APPROVAL")
    pdf.ln(2)
    col = 60
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col, 6, "  Prepared By")
    pdf.cell(col, 6, "Reviewed By")
    pdf.cell(col, 6, "Approved By")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(col, 6, "  HR Department")
    pdf.cell(col, 6, "Head Chef - Egy. Kitchen")
    pdf.cell(col, 6, "HR Manager")
    pdf.ln(8)
    pdf.cell(col, 6, "  Signature: ___________")
    pdf.cell(col, 6, "Signature: ___________")
    pdf.cell(col, 6, "Signature: ___________")
    pdf.ln(6)
    pdf.cell(col, 6, "  Date: _______________")
    pdf.cell(col, 6, "Date: _______________")
    pdf.cell(col, 6, "Date: _______________")
    pdf.ln(6)

    out = os.path.join(BASE, "JD-EGK-1011-Mona_Farag.pdf")
    pdf.output(out)
    print(f"✅ PDF generated: {out}")


generate_jd()
