"""
ROIN WORLD FZE — JD PDF Generator
Generates a Job Description PDF from a data dict.
"""

from fpdf import FPDF
from datetime import datetime
import io
import os

BASE = os.path.dirname(os.path.abspath(__file__))
LOGO = os.path.join(BASE, "company_logo.png")


def safe(text):
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
        "\u00b7": "*", "\u00a0": " ",
    }
    t = str(text)
    for old, new in replacements.items():
        t = t.replace(old, new)
    return t.encode("latin-1", errors="replace").decode("latin-1")


class JDPDF(FPDF):
    def header(self):
        if os.path.exists(LOGO):
            self.image(LOGO, x=85, y=8, w=25)
            self.ln(28)
        else:
            self.ln(10)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 6, "ROIN WORLD FZE EGYPT BRANCH", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, "Building No 1, Gamal Abdel Nasser Street - El Dabaa - Matrouh",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, "info.egypt@roinworld.com     www.roinworld.com",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(15, self.get_y() + 2, 195, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4,
            "This job description is not exhaustive and may be updated at any time by management.",
            align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4,
            safe(f"Generated by ROIN WORLD FZE HR System  -  {datetime.now().strftime('%d/%m/%Y %H:%M')}"),
            align="C")


def _section(pdf, title):
    pdf.set_fill_color(220, 220, 220)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_x(pdf.l_margin)
    pdf.cell(pdf.epw, 8, safe(f"  {title}"), new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)


def _field(pdf, label, value, label_w=55):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(label_w, 7, safe(f"  {label}:"))
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, safe(str(value)), new_x="LMARGIN", new_y="NEXT")


def _multiline(pdf, text):
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.epw, 6, safe(str(text)))


def generate_jd_pdf(data):
    """
    data keys: emp_code, full_name, job_title, department, manager_name,
               location, employment_type, grade, summary, tasks (list),
               qualifications, created_by, created_at
    Returns: bytes
    """
    pdf = JDPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "JOB DESCRIPTION", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 9)
    ec = data.get("emp_code", "")
    dept_code = "".join(w[0].upper() for w in str(data.get("department","X")).split()[:2])
    doc_no = f"JD-{dept_code}-{ec}"
    pdf.cell(0, 5, safe(f"Document No: {doc_no}     Effective Date: {data.get('created_at','-')}     Rev: 01"),
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # ── Position Information ─────────────────────────────────────────────────
    _section(pdf, "POSITION INFORMATION")
    _field(pdf, "Employee Name",   data.get("full_name", "-"))
    _field(pdf, "Employee Code",   data.get("emp_code", "-"))
    _field(pdf, "Job Title",       data.get("job_title", "-"))
    _field(pdf, "Department",      data.get("department", "-"))
    _field(pdf, "Reports To",      data.get("manager_name", "-"))
    _field(pdf, "Work Location",   data.get("location", "El Dabaa Nuclear Power Plant Site, Matrouh"))
    _field(pdf, "Employment Type", data.get("employment_type", "Full-Time"))
    _field(pdf, "Grade / Level",   data.get("grade", "-"))
    pdf.ln(4)

    # ── Job Summary ──────────────────────────────────────────────────────────
    _section(pdf, "1. JOB SUMMARY")
    pdf.set_font("Helvetica", "", 10)
    _multiline(pdf, data.get("summary", "-"))
    pdf.ln(4)

    # ── Key Responsibilities ─────────────────────────────────────────────────
    _section(pdf, "2. KEY RESPONSIBILITIES")
    pdf.set_font("Helvetica", "", 10)
    for i, task in enumerate(data.get("tasks", []), 1):
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(pdf.epw, 6, safe(f"{i}.  {task}"))
    pdf.ln(4)

    # ── Qualifications ───────────────────────────────────────────────────────
    _section(pdf, "3. REQUIRED QUALIFICATIONS")
    pdf.set_font("Helvetica", "", 10)
    _multiline(pdf, data.get("qualifications", "-"))
    pdf.ln(4)

    # ── Working Conditions ───────────────────────────────────────────────────
    _section(pdf, "4. WORKING CONDITIONS")
    pdf.set_font("Helvetica", "", 10)
    wc = data.get("working_conditions", "8:00 AM - 5:00 PM, 6 days per week. PPE required on site.")
    _multiline(pdf, wc)
    pdf.ln(4)

    # ── Approval ─────────────────────────────────────────────────────────────
    _section(pdf, "5. APPROVAL")
    pdf.ln(2)
    col = 60

    # Names row
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col, 6, safe(f"  Prepared By"))
    pdf.cell(col, 6, safe("Reviewed By"))
    pdf.cell(col, 6, safe("Approved By"))
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(col, 6, safe(f"  {data.get('created_by', 'HR Department')}"))
    pdf.cell(col, 6, safe(data.get("manager_name", "-")))
    pdf.cell(col, 6, safe(data.get("approver_name", "HR Manager")))
    pdf.ln(6)

    # Signature row — embed images if provided, else blank lines
    sigs = data.get("signatures", {})        # dict: "prepared" / "reviewed" / "approved" → bytes or None
    texts = data.get("sig_texts", {})        # dict: same keys → text fallback or None
    sig_y = pdf.get_y()

    for i, key in enumerate(["prepared", "reviewed", "approved"]):
        sb = sigs.get(key)
        st = texts.get(key, "")
        x  = pdf.l_margin + i * col + (2 if i == 0 else 0)
        if sb:
            try:
                img_io = io.BytesIO(sb)
                pdf.image(img_io, x=x, y=sig_y, h=10)
            except Exception:
                pass
        elif st:
            pdf.set_xy(x, sig_y)
            pdf.set_font("Helvetica", "I", 7)
            pdf.cell(col - 2, 5, safe(st))
            pdf.set_font("Helvetica", "", 9)

    pdf.set_y(sig_y + 12)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(col, 5, "  ___________________")
    pdf.cell(col, 5, "___________________")
    pdf.cell(col, 5, "___________________")
    pdf.ln(5)

    # Date row
    now_str = datetime.now().strftime("%d/%m/%Y")
    pdf.cell(col, 5, safe(f"  Date: {now_str}"))
    pdf.cell(col, 5, safe(f"Date: {now_str}"))
    pdf.cell(col, 5, safe(f"Date: {now_str}"))

    return pdf.output()
