"""
ROIN WORLD FZE — PDF Generator
================================
Uses fpdf2 with company logo. Outputs real PDF.
Shows approver names next to their status.
"""

from fpdf import FPDF
from datetime import datetime
import os
import io
import secrets


def safe(text):
    """Replace unicode chars that Helvetica can't handle."""
    if not text: return ""
    text = str(text)
    for old, new in {"\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
                     "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
                     "\u2713": "V", "\u2717": "X", "\u2714": "V", "\u2716": "X",
                     "\u00b7": "*", "\u2190": "<-", "\u2192": "->", "\u00a0": " ",
                     "\u2015": "-", "\u2012": "-", "\u2010": "-", "\u2011": "-",
                     "\u2500": "-", "\u2502": "|", "\u250c": "+", "\u2510": "+",
                     "\u2514": "+", "\u2518": "+", "\u00bb": ">>", "\u00ab": "<<",
                     "\u00b0": "o", "\u2103": "C", "\u2109": "F",
                     }.items():
        text = text.replace(old, new)
    # Strip any remaining non-latin1 chars
    return text.encode('latin-1', errors='replace').decode('latin-1')


class LeaveRequestPDF(FPDF):
    def __init__(self, logo_path=None):
        super().__init__()
        self.logo_path = logo_path

    def header(self):
        # Logo
        if self.logo_path and os.path.exists(self.logo_path):
            self.image(self.logo_path, x=85, y=8, w=25)
            self.ln(28)
        else:
            self.ln(10)

        # Company name
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 6, "ROIN WORLD FZE EGYPT BRANCH", new_x="LMARGIN", new_y="NEXT", align="C")

        # Address
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, safe("Building No 1, Gamal Abdel Nasser Street - El Dabaa - Matrouh"),
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, "info.egypt@roinworld.com     www.roinworld.com",
                  new_x="LMARGIN", new_y="NEXT", align="C")

        # Line
        self.line(15, self.get_y() + 2, 195, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4, "Generated by ROIN WORLD FZE HR System", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, safe(f"Generated: {datetime.now().strftime('%d/%m/%Y %H:%M')}"),
                  align="C")


def generate_leave_pdf(request_data):
    """
    Generate a PDF for approved or rejected leave request.
    request_data['approval_chain'] should have 'name' key for each approver.
    Returns: bytes
    """
    # Find logo
    logo = None
    for p in ["company_logo.png",
              os.path.join(os.path.dirname(os.path.abspath(__file__)), "company_logo.png")]:
        if os.path.exists(p):
            logo = p; break

    pdf = LeaveRequestPDF(logo_path=logo)
    pdf.add_page()

    final = request_data.get("final_status", "Unknown")
    is_approved = final == "Approved"

    # Title
    pdf.set_font("Helvetica", "B", 16)
    title = "LEAVE APPROVAL CERTIFICATE" if is_approved else "LEAVE REQUEST - REJECTED"
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(3)

    # Request info line
    pdf.set_font("Helvetica", "", 9)
    rid = safe(request_data.get("request_id", "-"))
    pdf.cell(95, 6, f"Request ID: {rid}")
    pdf.cell(95, 6, f"Date: {datetime.now().strftime('%d/%m/%Y')}", align="R",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Employee Details ──
    pdf.set_fill_color(230, 230, 230)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  EMPLOYEE DETAILS", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    for label, key in [("Name", "full_name"), ("Employee Code", "emp_code"), ("Department", "department")]:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, f"  {label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, safe(str(request_data.get(key, "-"))), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Leave Details ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  LEAVE DETAILS", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    details = [
        ("Type", f"{request_data.get('leave_type', '-')} Leave"),
        ("From", request_data.get("start_date", "-")),
        ("To", request_data.get("end_date", "-")),
        ("Working Days", str(request_data.get("working_days", "-"))),
        ("Reason", request_data.get("reason", "-")),
        ("Submitted", request_data.get("submitted_at", "-")),
    ]
    for label, value in details:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, f"  {label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, safe(str(value)), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Approval Chain ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "  APPROVAL CHAIN", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    for step in request_data.get("approval_chain", []):
        role   = step.get("role",   "-")
        status = step.get("status", "-")
        date   = step.get("date",   "")
        name   = step.get("name",   "")
        sig_bytes = step.get("sig_bytes")     # bytes or None
        sig_text  = step.get("sig_text", "")  # text fallback

        if status == "NA":
            continue

        if status == "Approved":
            icon = "[APPROVED]"
        elif status == "Rejected":
            icon = "[REJECTED]"
        else:
            icon = "[PENDING]"

        line = f"  {icon}  {role}"
        if name:
            line += f" ({safe(name)})"
        if date:
            line += f"  -  {safe(date)}"

        pdf.cell(0, 7, safe(line), new_x="LMARGIN", new_y="NEXT")

        # Embed signature if approved (high-quality: 4cm wide, name + date below)
        if status == "Approved":
            sig_placed = False
            if sig_bytes:
                try:
                    img_io = io.BytesIO(sig_bytes)
                    pdf.image(img_io, x=pdf.l_margin + 10, y=pdf.get_y(), w=40, h=16)
                    pdf.ln(18)
                    sig_placed = True
                except Exception:
                    pass
            if not sig_placed and sig_text:
                pdf.set_font("Helvetica", "I", 8)
                pdf.cell(0, 5, safe(f"  {sig_text}"), new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
            elif not sig_placed:
                pdf.cell(0, 5, "  ___________________", new_x="LMARGIN", new_y="NEXT")
            # Bold name + italic date below signature
            if name:
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(0, 4, safe(f"  {name}"), new_x="LMARGIN", new_y="NEXT")
            if date:
                pdf.set_font("Helvetica", "I", 8)
                pdf.cell(0, 4, safe(f"  {date}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
    pdf.ln(5)

    # ── Final Status ──
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 16)
    if is_approved:
        pdf.set_text_color(0, 120, 0)
        pdf.cell(0, 12, "FINAL STATUS: APPROVED", new_x="LMARGIN", new_y="NEXT", align="C")
    else:
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 12, "FINAL STATUS: REJECTED", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_text_color(0, 0, 0)

    if not is_approved:
        rej = request_data.get("rejection_reason", "")
        if rej:
            pdf.set_font("Helvetica", "", 10)
            pdf.ln(2)
            pdf.cell(0, 7, safe(f"Reason: {rej}"), new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.ln(8)

    # Verification code + reference
    ver_code = f"SIG-{secrets.token_hex(4).upper()}"
    pdf.set_font("Helvetica", "I", 7)
    pdf.cell(0, 4,
             safe(f"Ref: PDF-{datetime.now().strftime('%Y')}-{rid}   |   Verified: {ver_code}"),
             align="C")

    return pdf.output()
