"""
ROIN WORLD FZE — Transport PDF Generator
==========================================
Generates:
  1. Vehicle Service Request form (with progressive signatures)
  2. Commute Trip Assignment Summary

Uses same Helvetica + safe() pattern as pdf_generator.py
"""

from fpdf import FPDF
from datetime import datetime
import os
import io
import secrets


def safe(text):
    """Strip non-latin1 chars for Helvetica font."""
    if not text:
        return ""
    text = str(text)
    for old, new in {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
        "\u2713": "V", "\u2717": "X", "\u2714": "V", "\u2716": "X",
    }.items():
        text = text.replace(old, new)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _TransPDF(FPDF):
    def __init__(self, subtitle=""):
        super().__init__()
        self._subtitle = subtitle
        logo_p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "company_logo.png")
        self._logo = logo_p if os.path.exists(logo_p) else None

    def header(self):
        if self._logo:
            self.image(self._logo, x=85, y=8, w=25)
            self.ln(28)
        else:
            self.ln(10)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 6, "ROIN WORLD FZE EGYPT BRANCH", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, "Building No 1, Gamal Abdel Nasser Street - El Dabaa - Matrouh",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.cell(0, 5, "info.egypt@roinworld.com     www.roinworld.com",
                  new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(15, self.get_y() + 2, 195, self.get_y() + 2)
        self.ln(5)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 7, safe(self._subtitle), new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4, "Generated by ROIN WORLD FZE HR System",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Generated: {datetime.now().strftime('%d/%m/%Y %H:%M')}", align="C")


def _section(pdf, label):
    pdf.set_fill_color(220, 230, 245)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, f"  {label}", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(1)


def _row(pdf, label, value, w=55):
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(w, 6, f"  {label}:")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, safe(str(value)), new_x="LMARGIN", new_y="NEXT")


def _sig_block(pdf, role, status, date, name, sig_bytes=None, sig_text=None):
    if status == "NA":
        return
    icon = "[APPROVED]" if status == "Approved" else (
           "[REJECTED]" if status == "Rejected" else "[PENDING]")
    pdf.set_font("Helvetica", "B", 9)
    line = f"  {icon}  {safe(role)}"
    if name:
        line += f" ({safe(name)})"
    if date:
        line += f"  --  {safe(date)}"
    pdf.cell(0, 7, line, new_x="LMARGIN", new_y="NEXT")
    if status == "Approved":
        if sig_bytes:
            try:
                img_io = io.BytesIO(sig_bytes)
                pdf.image(img_io, x=pdf.l_margin + 10, y=pdf.get_y(), w=40, h=16)
                pdf.ln(18)
            except Exception:
                if sig_text:
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.cell(0, 5, safe(f"  {sig_text}"), new_x="LMARGIN", new_y="NEXT")
                else:
                    pdf.cell(0, 5, "  ___________________", new_x="LMARGIN", new_y="NEXT")
        elif sig_text:
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, safe(f"  {sig_text}"), new_x="LMARGIN", new_y="NEXT")
        if name:
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(0, 4, safe(f"  {name}"), new_x="LMARGIN", new_y="NEXT")
        if date:
            pdf.set_font("Helvetica", "I", 7)
            pdf.cell(0, 4, safe(f"  {date}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)


def generate_transport_request_pdf(data: dict) -> bytes:
    """
    Generate a Vehicle Service Request PDF at any approval stage.

    data keys (all optional — missing values shown as empty):
      request_id, submitted_at, requester_code, requester_name, requester_dept,
      trip_type (Near/Far), from_location, to_location, purpose, date,
      departure_time, passengers, notes,
      manager_status, manager_date, manager_name, manager_sig_bytes, manager_sig_text,
      director_status (NA/Pending/Approved/Rejected), director_date, director_name,
        director_sig_bytes, director_sig_text,
      transport_status, transport_date, transport_name, transport_sig_bytes, transport_sig_text,
      vehicle_plate, driver_name, final_status,
    """
    rid = data.get("request_id", "")
    pdf = _TransPDF(f"VEHICLE SERVICE REQUEST  |  {safe(rid)}")
    pdf.add_page()

    # ── Requester Details ──────────────────────────────────────────────────────
    _section(pdf, "REQUESTER DETAILS")
    _row(pdf, "Request ID",     data.get("request_id", ""))
    _row(pdf, "Submitted At",   data.get("submitted_at", ""))
    _row(pdf, "Employee Code",  data.get("requester_code", ""))
    _row(pdf, "Full Name",      data.get("requester_name", ""))
    _row(pdf, "Department",     data.get("requester_dept", ""))
    pdf.ln(2)

    # ── Trip Details ───────────────────────────────────────────────────────────
    _section(pdf, "TRIP DETAILS")
    trip_type = "Near - Local Sites" if data.get("trip_type") == "Near" else "Far - Remote City"
    _row(pdf, "Trip Type",       trip_type)
    _row(pdf, "From",            data.get("from_location", ""))
    _row(pdf, "To",              data.get("to_location", ""))
    _row(pdf, "Date",            data.get("date", ""))
    _row(pdf, "Departure Time",  data.get("departure_time", ""))
    _row(pdf, "Passengers",      str(data.get("passengers", "")))
    _row(pdf, "Purpose",         data.get("purpose", ""))
    if data.get("notes"):
        _row(pdf, "Notes",       data.get("notes", ""))
    pdf.ln(2)

    # ── Submitted By ──────────────────────────────────────────────────────────
    _section(pdf, "SUBMITTED BY")
    _sig_block(pdf, "Requester",
               "Approved",   # always "signed" by submitter
               data.get("submitted_at", ""),
               data.get("requester_name", ""),
               data.get("submitter_sig_bytes"),
               data.get("submitter_sig_text"))

    # ── Approval Chain ─────────────────────────────────────────────────────────
    _section(pdf, "APPROVAL CHAIN")
    _sig_block(pdf, "Direct Manager",
               data.get("manager_status", "Pending"),
               data.get("manager_date", ""),
               data.get("manager_name", ""),
               data.get("manager_sig_bytes"),
               data.get("manager_sig_text"))
    if data.get("director_status") not in ("NA", "", None):
        _sig_block(pdf, "Director",
                   data.get("director_status", "Pending"),
                   data.get("director_date", ""),
                   data.get("director_name", ""),
                   data.get("director_sig_bytes"),
                   data.get("director_sig_text"))
    _sig_block(pdf, "Transport Manager",
               data.get("transport_status", "Pending"),
               data.get("transport_date", ""),
               data.get("transport_name", ""),
               data.get("transport_sig_bytes"),
               data.get("transport_sig_text"))

    # ── Vehicle Assignment ─────────────────────────────────────────────────────
    if data.get("vehicle_plate"):
        pdf.ln(1)
        _section(pdf, "VEHICLE ASSIGNMENT")
        _row(pdf, "Vehicle Plate", data.get("vehicle_plate", ""))
        _row(pdf, "Driver",        data.get("driver_name", ""))

    # ── Footer verification ────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(2)
    code = secrets.token_hex(4).upper()
    pdf.set_font("Helvetica", "I", 7)
    status_lbl = safe(data.get("final_status", "In Progress"))
    pdf.cell(0, 5, f"Verification: VEH-{code}  |  Status: {status_lbl}", align="C")

    out = io.BytesIO()
    pdf.output(out)
    return out.getvalue()


def generate_commute_pdf(data: dict, vehicle_groups: list) -> bytes:
    """
    Generate a Commute Trip Assignment Summary PDF.

    data keys: commute_id, date, departure_time, from_location, to_location,
               employee_count, requester_name, submitted_at
    vehicle_groups: list of dicts:
      {"plate": str, "type": str, "driver_name": str, "capacity": int,
       "passengers": [{"code": str, "name": str, "dept": str}, ...]}
    """
    pdf = _TransPDF("COMMUTE TRIP ASSIGNMENT SUMMARY")
    pdf.add_page()

    _section(pdf, "TRIP DETAILS")
    _row(pdf, "Commute ID",      data.get("commute_id", ""))
    _row(pdf, "Submitted At",    data.get("submitted_at", ""))
    _row(pdf, "Requested by",    data.get("requester_name", ""))
    _row(pdf, "Date",            data.get("date", ""))
    _row(pdf, "Departure Time",  data.get("departure_time", ""))
    _row(pdf, "From",            data.get("from_location", ""))
    _row(pdf, "To",              data.get("to_location", ""))
    _row(pdf, "Total Passengers", str(data.get("employee_count", "")))
    pdf.ln(3)

    total_assigned = sum(len(vg.get("passengers", [])) for vg in vehicle_groups)
    total_emp = data.get("employee_count", 0)
    unassigned_count = int(total_emp) - total_assigned if total_emp else 0

    for vg in vehicle_groups:
        plate   = vg.get("plate", "")
        vtype   = vg.get("type", "")
        driver  = vg.get("driver_name", "")
        cap     = vg.get("capacity", "")
        pax     = vg.get("passengers", [])

        pdf.set_fill_color(30, 80, 160)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        header_txt = (f"  {safe(plate)}  |  {safe(vtype)}  |  "
                      f"Capacity: {cap}  |  Driver: {safe(driver)}  "
                      f"|  Assigned: {len(pax)}/{cap}")
        pdf.cell(0, 7, header_txt, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)

        pdf.set_fill_color(230, 237, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(10, 6, "#",    border=1, fill=True)
        pdf.cell(30, 6, "Code", border=1, fill=True)
        pdf.cell(85, 6, "Name", border=1, fill=True)
        pdf.cell(65, 6, "Department", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 8)
        for i, p in enumerate(pax, 1):
            bg = i % 2 == 0
            if bg:
                pdf.set_fill_color(245, 248, 255)
            pdf.cell(10, 6, str(i),                          border=1, fill=bg)
            pdf.cell(30, 6, safe(str(p.get("code", ""))),    border=1, fill=bg)
            pdf.cell(85, 6, safe(str(p.get("name", ""))[:42]), border=1, fill=bg)
            pdf.cell(65, 6, safe(str(p.get("dept", ""))[:30]), border=1, fill=bg,
                     new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    if unassigned_count > 0:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, f"  NOTE: {unassigned_count} employee(s) not yet assigned to a vehicle.",
                 new_x="LMARGIN", new_y="NEXT")

    out = io.BytesIO()
    pdf.output(out)
    return out.getvalue()
